#ifndef EXECGLUE_INTERFACE_DEF_H
#define EXECGLUE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 50.13.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_EXECGLUE_H
#include <libraries/execglue.h>
#endif

struct ExecGlueIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct ExecGlueIFace *Self);
	ULONG APICALL (*Release)(struct ExecGlueIFace *Self);
	void APICALL (*Expunge)(struct ExecGlueIFace *Self);
	struct Interface * APICALL (*Clone)(struct ExecGlueIFace *Self);
	VOID APICALL (*GetCPUInfo)(struct ExecGlueIFace *Self, struct TagItem * tagList);
	VOID APICALL (*GetCPUInfoTags)(struct ExecGlueIFace *Self, ...);
};

#endif /* EXECGLUE_INTERFACE_DEF_H */
